pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://jitpack.io")
            content {
                includeModule("com.github.teamnewpipe", "NewPipeExtractor")
                includeGroup("com.github.teamnewpipe.NewPipeExtractor")
                includeGroup("com.github.TeamNewPipe.NewPipeExtractor")
                includeModule("com.github.TeamNewPipe", "nanojson")
            }
        }
    }
}

rootProject.name = "ssYouTube"
include ':app'
