package com.skystream.ssyoutube;

/** Tracking tokens and account credentials stay in the YouTube document, never in native code. */
final class NativeWatchHistoryScript {
    private static final String TRUSTED_PAGE =
            "window.top===window&&location.protocol==='https:'"
                    + "&&(!location.port||location.port==='443')"
                    + "&&/^(www\\.|m\\.|music\\.)?youtube\\.com$/.test(location.hostname)";

    static final String SCRIPT = "(function(){"
            + "if(!(" + TRUSTED_PAGE + ")||window.__ssyoutubeWatchHistory){return;}"
            + "var active=null,initial=true,page=location.href,blocked=null;"
            + "function invalidate(){initial=false;"
            + "blocked=window.ytInitialPlayerResponse;}"
            + "window.addEventListener('yt-navigate-start',invalidate,true);"
            + "window.addEventListener('popstate',invalidate);"
            + "function pageId(){var url=new URL(location.href);"
            + "if(url.pathname==='/watch'){return url.searchParams.get('v');}"
            + "var match=url.pathname.match(/^\\/(shorts|live|embed)\\/([A-Za-z0-9_-]{11})\\/?$/);"
            + "return match?match[2]:null;}"
            + "function account(){try{var cfg=window.ytcfg;if(!cfg||!cfg.get){return null;}"
            + "var index=cfg.get('SESSION_INDEX'),logged=cfg.get('LOGGED_IN');"
            + "if(typeof logged!=='boolean'||(typeof index!=='string'&&typeof index!=='number'))"
            + "{return null;}return JSON.stringify([index,cfg.get('DELEGATED_SESSION_ID'),logged]);"
            + "}catch(e){return null;}}"
            + "function endpoint(value,path,id){try{"
            + "if(typeof value!=='string'||value.length>16384){return null;}"
            + "var url=new URL(value,location.origin);"
            + "if(url.protocol!=='https:'||url.username||url.password||url.hash"
            + "||(url.port&&url.port!=='443')"
            + "||!/^(www\\.|m\\.|music\\.|s\\.)?youtube\\.com$/.test(url.hostname)"
            + "||url.pathname!==path){return null;}"
            + "var ids=url.searchParams.getAll('docid');"
            + "if(ids.some(function(value){return value!==id;})){return null;}"
            + "return url.href;}catch(e){return null;}}"
            + "function tracking(id){"
            + "if(pageId()!==id){return null;}"
            + "var candidates=[],nodes=document.querySelectorAll("
            + "'#movie_player,#player,ytm-player,ytm-watch,ytm-app');"
            + "for(var i=0;i<nodes.length;i++){try{"
            + "if(typeof nodes[i].getPlayerResponse==='function'){"
            + "candidates.push(nodes[i].getPlayerResponse());}"
            + "if(nodes[i].data){candidates.push(nodes[i].data.playerResponse);}"
            + "}catch(e){}}"
            + "if(initial){candidates.push(window.ytInitialPlayerResponse);"
            + "try{var args=window.ytplayer&&window.ytplayer.config&&window.ytplayer.config.args;"
            + "if(args&&args.player_response){candidates.push(typeof args.player_response==='string'?"
            + "JSON.parse(args.player_response):args.player_response);}}catch(e){}}"
            + "for(var j=0;j<candidates.length;j++){var response=candidates[j];"
            + "if(!response||response===blocked||!response.videoDetails"
            + "||response.videoDetails.videoId!==id||!response.playbackTracking){continue;}"
            + "var data=response.playbackTracking;"
            + "var playback=endpoint(data.videostatsPlaybackUrl&&"
            + "data.videostatsPlaybackUrl.baseUrl,'/api/stats/playback',id);"
            + "var watchtime=endpoint(data.videostatsWatchtimeUrl&&"
            + "data.videostatsWatchtimeUrl.baseUrl,'/api/stats/watchtime',id);"
            + "if(playback&&watchtime){return {playback:playback,watchtime:watchtime};}}"
            + "return null;}"
            + "function nonce(){var bytes=new Uint8Array(16);crypto.getRandomValues(bytes);"
            + "var chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_',out='';"
            + "for(var i=0;i<bytes.length;i++){out+=chars[bytes[i]&63];}return out;}"
            + "function send(base,context,report,watchtime){"
            + "var url=new URL(base),params=url.searchParams;"
            + "params.set('docid',context.id);params.set('cpn',context.cpn);params.set('ver','2');"
            + "params.set('cmt',report.position);"
            + "if(report.duration>0){params.set('len',report.duration);}"
            + "params.set('rt',((performance.now()-context.started)/1000).toFixed(3));"
            + "if(watchtime){params.set('st',report.starts);params.set('et',report.ends);"
            + "params.set('state',report.playing?'playing':'paused');"
            + "params.set('final',report.playing?'0':'1');"
            + "}else{params.set('rtn','0');}"
            + "var controller=new AbortController();"
            + "var timer=setTimeout(function(){controller.abort();},8000);"
            + "return fetch(url.href,{method:'GET',credentials:'include',mode:'no-cors',"
            + "redirect:'error',cache:'no-store',signal:controller.signal})"
            + ".then(function(response){if(response.type!=='opaque'&&!response.ok){throw Error();}})"
            + ".finally(function(){clearTimeout(timer);});}"
            + "window.__ssyoutubeWatchHistory=function(id,session,report){try{"
            + "if(!(" + TRUSTED_PAGE + ")||!/^[A-Za-z0-9_-]{11}$/.test(id)){return;}"
            + "if(page!==location.href){invalidate();page=location.href;}"
            + "var identity=account();"
            + "if(active&&active.account!==identity){invalidate();}"
            + "if(!active||active.id!==id||active.session!==session||active.account!==identity){"
            + "active={id:id,session:session,account:identity,cpn:nonce(),"
            + "started:performance.now(),urls:null,sent:false,busy:false};}"
            + "var current=pageId();"
            + "if(current&&current!==id){active.urls=null;return;}"
            + "if(!current&&identity===null){active.urls=null;return;}"
            + "if(!active.urls){active.urls=tracking(id);}"
            + "if(!report||!active.urls||active.busy){return;}"
            + "if(!Number.isFinite(report.position)||report.position<0"
            + "||!Number.isFinite(report.duration)||report.duration<0"
            + "||typeof report.starts!=='string'||typeof report.ends!=='string'"
            + "||report.starts.length>2048||report.ends.length>2048"
            + "||!/^\\d+(\\.\\d+)?(,\\d+(\\.\\d+)?)*$/.test(report.starts)"
            + "||!/^\\d+(\\.\\d+)?(,\\d+(\\.\\d+)?)*$/.test(report.ends)){return;}"
            + "var context=active;context.busy=true;"
            + "var begin=context.sent?Promise.resolve():"
            + "send(context.urls.playback,context,report,false).then(function(){context.sent=true;});"
            + "begin.then(function(){"
            + "if(active!==context||account()!==context.account"
            + "||(!pageId()&&context.account===null)"
            + "||(pageId()&&pageId()!==context.id)){return;}"
            + "return send(context.urls.watchtime,context,report,true);"
            + "}).catch(function(){}).finally(function(){context.busy=false;});"
            + "}catch(e){}};"
            + "})()";

    static String update(String id, long session, NativeWatchHistoryState.Report report) {
        if (!NativePlaybackState.isVideoId(id)) {
            return "";
        }
        String data = report == null ? "null" : "{position:"
                + NativeWatchHistoryState.seconds(report.positionMs) + ",duration:"
                + NativeWatchHistoryState.seconds(report.durationMs) + ",starts:'"
                + report.starts + "',ends:'" + report.ends + "',playing:" + report.playing + "}";
        return "(function(){if(" + TRUSTED_PAGE + "&&window.__ssyoutubeWatchHistory){"
                + "window.__ssyoutubeWatchHistory('" + id + "'," + session + "," + data + ");}})()";
    }

    private NativeWatchHistoryScript() { }
}
